version: "3"
services:
  nginx:
    image: nginx:1.15.7-alpine
    container_name: nginx1.15
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    networks:
      - default


networks:
  default:
